### ISSUE TITLE
compilation error - hold_console_for_windows

### ISSUE THREAD

**Issue by photomedia** [josiahseaman/DDV#55]
I cloned the python-master branch, and attempted to run before making any changes.
Unfortunately, there is a compilation error right out of the gate:

Running in: c:\DATA\fluentDNA\DDV
Traceback (most recent call last):
  File "c:\DATA\fluentDNA\DDV\fluentdna.py", line 48, in <module>
    from DDV.DDVUtils import create_deepzoom_stack, make_output_dir_with_suffix, base_directories, \
ImportError: cannot import name 'hold_console_for_windows'

I'm attempting to run the code on Windows 10, Python 3.6 (32 bit).

**Comment by josiahseaman** [comment]
What's your diagnosis?  That method was introduced in 1e9e250de40801ea2cef58068c80b916dd4e01a1 back in February.  It's definitely in the repository.  Perhaps it's not that specific method but simply that it can't find "DDV" at all?  That method doesn't exist in the pip branch since the python-master branch hasn't received the full gamut of testing yet.

**Comment by photomedia** [comment]
My diagnosis is that it can't find "DDV" at all, and it lists this method because it's the first one called.  I was trying to set this up as a workspace using Visual Studio Code (https://code.visualstudio.com/), but the same error is thrown if I try to run fluentdna.py outside of that IDE as well.  
I see now this was just a path issue.  I needed to move fluentdna.py up to the parent folder, out of the DDV folder, and then it works.

**Comment by josiahseaman** [comment]
I'm sorry to say I think that's the expected behavior if you just extracted the files.  The pip install command 
`pip install --process-dependency-links git+https://github.com/josiahseaman/FluentDNA.git@python-master` 
actually puts these files in the `site-packages` folder which is in your PYTHONPATH.  I believe your current directory is not in PYTHONPATH for the same security reason Linux doesn't include ./ in PATH.  `pip` is also linked to the currently activated python environment.  

I don't know about visual studio, but you can [Download Pycharm Community](https://www.jetbrains.com/pycharm/download/#section=windows) edition for free.  It automatically does some trick, I believe adding the project directory to the PYTHONPATH.  For development, this is the way to go.  End users will use pip for now.  I was just thinking it'd be nice to have a frozen install (cx_freeze) .exe file or some kind of container so users don't need to know about all this dev environment non-sense.
